# Generated by Django 4.2.5 on 2023-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='null.jpg', upload_to='image')),
                ('Image1', models.ImageField(default='null.jpg', upload_to='image')),
                ('Image2', models.ImageField(default='null.jpg', upload_to='image')),
                ('Image3', models.ImageField(default='null.jpg', upload_to='image')),
                ('Image4', models.ImageField(default='null.jpg', upload_to='image')),
                ('Image5', models.ImageField(default='null.jpg', upload_to='image')),
                ('Service1', models.CharField(default='', max_length=600)),
                ('Service2', models.CharField(default='', max_length=600)),
                ('Service3', models.CharField(default='', max_length=600)),
                ('Service4', models.CharField(default='', max_length=600)),
                ('Service5', models.CharField(default='', max_length=600)),
                ('Service6', models.CharField(default='', max_length=600)),
                ('Price1', models.IntegerField()),
                ('Price2', models.IntegerField()),
                ('Price3', models.IntegerField()),
                ('Price4', models.IntegerField()),
                ('Price5', models.IntegerField()),
                ('Price6', models.IntegerField()),
            ],
        ),
    ]
