# Generated by Django 4.2.5 on 2023-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salons',
        ),
    ]
