# Generated by Django 4.2.5 on 2023-11-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='Category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
