# Generated by Django 4.2.5 on 2023-11-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_salons_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
                ('CategoryLocation', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Category',
        ),
    ]
