# Generated by Django 4.2.5 on 2023-11-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_category_remove_salons_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CategoryLocation',
        ),
    ]
