# Generated by Django 4.2.5 on 2023-11-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_remove_category_categorylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category'),
        ),
    ]
