# Generated by Django 4.2.5 on 2023-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_salons_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_Services', models.CharField(max_length=60)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Price1',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Price2',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Price3',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Price4',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Price5',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Price6',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Service1',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Service2',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Service3',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Service4',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Service5',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='Service6',
        ),
    ]
