# Generated by Django 4.2.5 on 2023-12-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_services_remove_salons_price1_remove_salons_price2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='salonid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.salons'),
        ),
    ]
