# Generated by Django 4.2.5 on 2023-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_services_salonid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='salonid',
        ),
        migrations.AddField(
            model_name='services',
            name='salon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
