# Generated by Django 4.2.5 on 2023-12-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_remove_services_salonid_services_salon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='salon',
        ),
        migrations.AddField(
            model_name='salons',
            name='serviceid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.services'),
        ),
    ]
