# Generated by Django 4.2.5 on 2023-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_remove_services_salon_salons_serviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salons',
            name='categoryid',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='serviceid',
        ),
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='Image1',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='Image2',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='Image3',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='Image4',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='Image5',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
    ]
