# Generated by Django 4.2.5 on 2023-12-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_remove_salons_categoryid_remove_salons_serviceid_and_more'),
        ('user', '0010_remove_bookingform_status_remove_bookingform_salonid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salons',
        ),
    ]
