# Generated by Django 4.2.5 on 2023-12-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_delete_salons'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category'),
        ),
    ]
