# Generated by Django 4.2.5 on 2023-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_services_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='categoryid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
