# Generated by Django 4.2.5 on 2023-12-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0015_alter_services_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
