# Generated by Django 4.2.5 on 2023-12-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_rename_category_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Image5',
        ),
    ]
