# Generated by Django 4.2.5 on 2023-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0017_remove_category_image1_remove_category_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Image',
            field=models.ImageField(default='null.jpg', upload_to='image'),
        ),
    ]
