# Generated by Django 4.2.5 on 2023-11-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Message',
            field=models.CharField(max_length=300),
        ),
    ]
