# Generated by Django 4.2.5 on 2023-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_feedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LName', models.CharField(max_length=30)),
                ('FName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('PhNo', models.IntegerField()),
                ('Address1', models.CharField(max_length=30)),
                ('Address2', models.CharField(max_length=30)),
                ('Address3', models.CharField(max_length=30)),
            ],
        ),
    ]
