# Generated by Django 4.2.5 on 2023-11-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_salons_categoryid'),
        ('user', '0005_bookingform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='PhNo',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='salonid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.salons'),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.register'),
        ),
    ]
