# Generated by Django 4.2.5 on 2023-11-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_servicedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDate',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='Service',
            field=models.CharField(default='', max_length=60),
        ),
    ]
