# Generated by Django 4.2.5 on 2023-12-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_remove_salons_categoryid_remove_salons_serviceid_and_more'),
        ('user', '0009_bookingform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='salonid',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='serviceid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.services'),
        ),
    ]
