# Generated by Django 4.2.5 on 2023-12-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_bookingform_status_remove_bookingform_salonid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='Service',
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='Date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
